[programs.localnet]
buildspace_gif_wall = "DkZNiYb8jAQJA4qdPmhn8dutfHsGbwVMb1zNoSQceBkq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/dimfeld/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
